migrated datacheck into gp2, reworked server, added configs for datacheck functions
Nocturnalmc/gp2 pull request #17
Opened 2022-03-13 14:46 UTC by c4lyp5o

alhamdulillah. please review. ada bberapa benda mcm hyperlinks aku belum update. tp so far aku check so good inshaaAllah. kalau ada apa2 bgtau ya. aku x integrate lg authcheck untuk route generatereten. nnt dah ada tweaking sikit, aku add auth tu.

2022-03-16 00:32 UTC, Nocturnalmc commented on server.js
> +        connectDB(process.env.MONGO_URI)
@c4lyp5o yang ni sepatutnya kena ada "await" before connectDB sebab kalau x nnti server akan jalan dlu before database succesfully connect

**Console output
kalau xda "await" :**
Server is listening at port: 3000. Lessgo!
Connected to Giret Database!

**kalau ada "await" :**
Connected to Giret Database!
Server is listening at port: 3000. Lessgo!

2022-03-16 00:38 UTC, c4lyp5o commented on server.js
> +        connectDB(process.env.MONGO_URI)
Ok mantap dato. Kejap aku buat changes.

2022-03-16 00:43 UTC, Nocturnalmc commented on server.js
> +        connectDB(process.env.MONGO_URI)
mantap dato nnti add commit baru

2022-03-16 00:46 UTC, Nocturnalmc commented on server.js
> +const cookieParser = require('cookie-parser');
@c4lyp5o btw dato nak pakai cookie utk authenticate user ka. currently aku guna jsonwebtoken dalam tu dah ada data sapa yang login, negeri mana etc2

2022-03-16 00:51 UTC, c4lyp5o commented on server.js
> +const cookieParser = require('cookie-parser');
Aku x pandai lg nk set headers guna axios. Aku guna cookie tu ntuk page generate reten shj

2022-03-16 01:15 UTC, Nocturnalmc commented on .gitignore
> +/public/exports
@c4lyp5o To be removed

2022-03-16 01:19 UTC, Nocturnalmc commented on server.js
> +const cookieParser = require('cookie-parser');
aku rasa kita stick dgn jsonwebtoken dato. sbb jadi double work pulak nak setup user identity kalau nak guna jwt dan cookie. satu lagi security setup nak kena double work jugak kalau pakai jwt dan cookie

agak2 boleh integrate ke jwt dalam pug?

2022-03-16 01:44 UTC, Nocturnalmc commented on database/connect.js
> +    return mongoose.connect(url, { useNewUrlParser: true, useUnifiedTopology: true });
@c4lyp5o dato code "{ useNewUrlParser: true, useUnifiedTopology: true }" x perlu dah since kita pakai mongoose v6

sini reference dia https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options

2022-03-16 02:26 UTC, Nocturnalmc commented on public/modules/dashboard.html
> +    <title>Dashboard - Gi-Ret 2.0</title>
@c4lyp5o dato saja tanya. sistem baru mmg xda PSY eh. kalau xda nnti dah finalize semua aku edit buang PSY kat semua page

perasan jgk kat package.json & package-lock.json "psy" dah xda

dan version number nak jadi 1.5.0 ka

2022-03-16 02:28 UTC, c4lyp5o commented on database/connect.js
> +    return mongoose.connect(url, { useNewUrlParser: true, useUnifiedTopology: true });
Terbaik dato. Aku change.

2022-03-16 02:28 UTC, c4lyp5o commented on public/modules/dashboard.html
> +    <title>Dashboard - Gi-Ret 2.0</title>
Xperlu dah. Up version sbb dah masuk generate 😆

2022-03-16 02:33 UTC, Nocturnalmc commented on database/connect.js
> +    return mongoose.connect(url, { useNewUrlParser: true, useUnifiedTopology: true });
baik dato paduu

2022-03-16 02:34 UTC, Nocturnalmc commented on public/modules/dashboard.html
> +    <title>Dashboard - Gi-Ret 2.0</title>
hahaha terbaik

2022-03-16 02:36 UTC, Nocturnalmc commented
@c4lyp5o dato folder unrelatedReferences nnti boleh restore balik tak. sbb dalam tu ada detail code form yang naim dan izzudin dah buat. nnti senang nak copy paste utk kita kembangkan kepada reten sekolah & young adult

2022-03-16 02:37 UTC, c4lyp5o commented
Ok baik

2022-03-16 02:50 UTC, Nocturnalmc commented on public/resources/script.js
> +  });
@c4lyp5o dato public/resources/script.js & public/resources/style.css pakai dalam pug view ka

2022-03-16 02:51 UTC, Nocturnalmc commented on public/resources/script.js
> +$(document).ready(function(){
@c4lyp5o dato public/resources/script.js & public/resources/style.css pakai dalam pug view ka

2022-03-16 02:52 UTC, c4lyp5o commented on public/resources/script.js
> +$(document).ready(function(){
Aah dato.

2022-03-16 02:55 UTC, Nocturnalmc commented on public/resources/script.js
> +$(document).ready(function(){
okay baik dato. mungkin kena perlu perubahan nama file utk mudah future readability. tapi takpa fokus dlu setel generate daripada download button tu

btw nak kena belajar pug ni >.<

2022-03-16 02:59 UTC, c4lyp5o commented on public/resources/script.js
> +$(document).ready(function(){
😆
Jom kita belajar sama2. Mcm best pug ni.

2022-03-16 03:07 UTC, Nocturnalmc requested changes
@c4lyp5o okay dato tu je review dari aku. so far yang kat routes, controllers, middlewares dan view yang berkaitan dengan pug je aku belum fahamkan. petang ni nak belajar dengan dato

yg komen2 nnti aku resolve lepas dato dah commit changes berkaitan dgn komen tu

2022-03-16 06:54 UTC, c4lyp5o commented on .gitignore
> +/public/exports
done

2022-03-17 03:01 UTC, Nocturnalmc commented
Eh dato mmg close ke. Tertekan ke

2022-03-17 03:11 UTC, c4lyp5o commented
Dato kata nk commit kt branch ni je kan. Kita pakai ni dlu nnt dah habis oter kita merge.

2022-03-17 03:15 UTC, Nocturnalmc commented
Eh xpe dato pull req ni keep open ja kita nampak dia punya flow error and correction kat mana nnti

Yg aku punya download button tu nnti aku buat branch lain base on branch amalgamated ni. Then nnti aku pull req utk merge dgn branch amalgamated ni utk dato review

2022-03-23 13:12 UTC, Nocturnalmc approved these changes
LGTM yo dato !

2022-03-23 13:12 UTC, merged