C4lyp5o
nocturnalmc/gp2 pull request #4358
Opened 2023-05-01 07:45 UTC by c4lyp5o

2023-05-01 07:45 UTC, c4lyp5o commented
@nocturnalmc mohon pengecekkan nya tuan yg mulia

2023-05-03 00:57 UTC, nocturnalmc requested changes
Move to env

2023-05-03 00:58 UTC, nocturnalmc commented on controllers/adminAPI.js
> +    (adminUser.negeri === 'Perlis' || adminUser.daerah === 'Arau')
to env

2023-05-03 03:26 UTC, c4lyp5o commented on controllers/adminAPI.js
> +    (adminUser.negeri === 'Perlis' || adminUser.daerah === 'Arau')
fixed in [fix: buang kod yang tidak 'diperlukan'](https://github.com/nocturnalmc/gp2/pull/4358/commits/cabc4ee9599ea120ab7e6352074f1073ec4f732c)

2023-05-05 03:02 UTC, nocturnalmc approved these changes

2023-05-05 03:43 UTC, merged