Dvachini
nocturnalmc/gp2 pull request #4868
Opened 2023-05-30 03:18 UTC by Dvachini

kasi push jap .matron nak tengok form pemeriksaan umum - (tidak disaring)

2023-05-30 03:29 UTC, c4lyp5o submitted a review, later dismissed
nmpk padu bismillah

2023-05-30 03:30 UTC, nocturnalmc requested changes
Beberapa soalan

2023-05-30 03:30 UTC, nocturnalmc commented on client/src/user/context/userAppContext.jsx
> +      portalId='root-portal'
Yg ni apa effect dia eh nnti din @Dvachini

2023-05-30 03:30 UTC, nocturnalmc commented on client/src/user/components/sekolah/UserTambahKemaskiniPelajarSekolah.jsx
> +  const howOldAreYouMyFriendtahunV2 = (date) => {
Eh silap din. Utk sekolah ni umur x perlu ikut tarikh lahir. Just ikut tahun lahir je @Dvachini 

Tp kena confirm balik dgn matron

2023-05-30 03:31 UTC, nocturnalmc commented
> nmpk padu bismillah

Ko laju je eh approve haha

2023-05-30 03:32 UTC, Dvachini commented on client/src/user/components/sekolah/UserTambahKemaskiniPelajarSekolah.jsx
> +  const howOldAreYouMyFriendtahunV2 = (date) => {
@nocturnalmc Ooo okayy yan .jap aku betulkan balik yg ni

2023-05-30 03:33 UTC, nocturnalmc commented on client/src/user/components/sekolah/UserTambahKemaskiniPelajarSekolah.jsx
> +  const howOldAreYouMyFriendtahunV2 = (date) => {
@Dvachini seigt aku matron ckp gitu lah. Kalau betul ko ubah lah din. Kalau aku salah ko keep ja umur kira mcm ni

2023-05-30 03:35 UTC, Dvachini commented on client/src/user/context/userAppContext.jsx
> +      portalId='root-portal'
@nocturnalmc Nnti yang ni .kalau calendar tu tak terpotong dekat modal

2023-05-30 03:36 UTC, nocturnalmc commented on client/src/user/context/userAppContext.jsx
> +      portalId='root-portal'
Oo menarik. Calendar yg dalam modal eh @Dvachini

2023-05-30 17:09 UTC, Dvachini commented
mohon kawan2 approve

2023-05-31 00:45 UTC, nocturnalmc commented
> mohon kawan2 approve

Okay jap aku review @Dvachini

2023-05-31 00:50 UTC, nocturnalmc approved these changes
TambahKemaskiniPelajarSekolah.jsx perlu perubahan tapi yang ni aku approve dlu utk changes yang lain @Dvachini

2023-05-31 00:50 UTC, nocturnalmc commented on client/src/user/components/sekolah/UserTambahKemaskiniPelajarSekolah.jsx
> +  const findAgeFromIc = (ic) => {
@Dvachini din maksud aku bukan cmni hahahah. Japgi kita vc lah

2023-05-31 01:19 UTC, merged