Dvachini
nocturnalmc/gp2 pull request #5049
Opened 2023-06-10 15:05 UTC by Dvachini

penambahan condition dalam form pemeriksaan

2023-06-10 15:20 UTC, nocturnalmc requested changes
Reviewed @Dvachini

2023-06-10 15:20 UTC, nocturnalmc commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +      toast.info(message, {
Din mmg kena buat cmni ke? Apa beza dia dgn cuma bagi toast.error then return @Dvachini

2023-06-10 15:20 UTC, nocturnalmc commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +  const checkTPRKesSelesai = async (e) => {
Kalau x perlu await data tu function ni x perlu async din @Dvachini

2023-06-10 15:20 UTC, nocturnalmc commented on client/src/user/components/umum/form-umum/Pemeriksaan.jsx
> +                {/* {props.jenisFasiliti === 'taska-tadika' && (
Dah xda eh din enggan tidak hadir ni terus buang ke @Dvachini

2023-06-10 22:51 UTC, Dvachini commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +  const checkTPRKesSelesai = async (e) => {
Aku buat camni ingat nak asynchonous .kalau aku try yg return tu ,setKesSelesai tak berubah .apa pendapat ko yan @nocturnalmc

2023-06-10 22:52 UTC, Dvachini commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +      toast.info(message, {
Aku ingat nak simplified @nocturnalmc

2023-06-10 22:53 UTC, Dvachini commented on client/src/user/components/umum/form-umum/Pemeriksaan.jsx
> +                {/* {props.jenisFasiliti === 'taska-tadika' && (
Mmg dri dulu patut kena buang .kalau budak tak dtg ptut tak paya h daftar @nocturnalmc

2023-06-10 23:02 UTC, nocturnalmc commented on client/src/user/components/umum/form-umum/Pemeriksaan.jsx
> +                {/* {props.jenisFasiliti === 'taska-tadika' && (
Oo. Orait mantap @Dvachini

2023-06-10 23:03 UTC, nocturnalmc commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +  const checkTPRKesSelesai = async (e) => {
Oo. Nti aku test harini. Btw form umum ko buang tak lagi yg checkbox tpr? @Dvachini

2023-06-10 23:13 UTC, Dvachini commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +  const checkTPRKesSelesai = async (e) => {
Aku comment out tpr umum tu dulu .sbb nnti aku nk buat kes selesai dkat umum gak

2023-06-10 23:14 UTC, nocturnalmc commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +  const checkTPRKesSelesai = async (e) => {
Line mana eh din aku x jumpa dalam PR ni haha @Dvachini

2023-06-11 22:26 UTC, nocturnalmc approved these changes
@Dvachini ni aku approve dlu nnti kita discuss lain berkenaan form umum punya TPR

2023-06-11 22:44 UTC, merged