Dvachini
nocturnalmc/gp2 pull request #5141
Opened 2023-06-14 08:41 UTC by Dvachini

Mohon review code ini kawan2 untuk form sekolah

2023-06-14 23:42 UTC, nocturnalmc requested changes
Sm sm luls @Dvachini

2023-06-14 23:42 UTC, nocturnalmc commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +        ) {
@Dvachini din ni kena buat explicit if block tu xleh else sbb cuba ko try condition umur bawah 10 tahun & status oku tu !== :

2023-06-14 23:42 UTC, Dvachini commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +        ) {
okayy jap

2023-06-14 23:45 UTC, Dvachini commented on client/src/user/components/sekolah/form-sekolah/UserFormSekolahPemeriksaan.jsx
> +        ) {
@nocturnalmc else okayy yan .kalau pakai block tu tak keluar toast tu

2023-06-15 01:20 UTC, nocturnalmc approved these changes

2023-06-15 01:20 UTC, nocturnalmc commented
@Dvachini bismillah boleh masuk dah ni

2023-06-15 01:20 UTC, merged